---
# Add tasks to generate and configure an SSL certificate and a private key here
# Add tasks to configure nginx as a reverse proxy here
# Add vhosts and other necessary files in the files/ and/or templates/ directories as appropriate
# Use handlers to restart nginx if necessary

# - name: Print message
#   ansible.builtin.debug:
#     msg: Please remove me

- name: Create Nginx Directory
  become: yes
  file:
    path: /etc/nginx/ssl
    state: directory
    
- name: Create private key (RSA, 4096)
  become: yes
  community.crypto.openssl_privatekey:
    path: "{{ pk_dir }}"
  
- name: Create a self-signed certificate
  become: yes
  community.crypto.x509_certificate:
    path: "{{ certificate_dir }}"
    privatekey_path: "{{ pk_dir }}"
    provider: selfsigned

- name: Configure Nginx as reverse proxy
  become: yes
  copy:
    src: files/default.conf
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Creating a hard link in sites-enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Nginx


